### ISSUE TITLE
Classic class

### ISSUE THREAD

**Issue by bycop** [Nicoxx45/tictactoe-game#3]
Hello,
i want to integrate your api in a discordjs bot.
But i have this error : Classic is not a constructor and i have put that on the start of the code
```
const Classic = require('a-js-tictactoe')
const game = new Classic();
const playerX = 'Nicolas';
const playerO = 'Louise';
```
Thanks if you can help me

**Comment by Nicoxx45** [comment]
Hi!
You made a mistake.
This is `const { Classic } = require('a-js-tictactoe')`.
I hope this will help you :+1:

**Comment by bycop** [comment]
Do you have a discord or other to talk instantly ? I have some others questions.
Thanks

**Comment by Nicoxx45** [comment]
Contact me on Discord: NicoTine#6105
